---
title: |
  Computer Intensive Methods
  Final project 3
author:   
  - My-Luong Vuong  
format: 
  pdf:
    documentclass: article
    fig-pos: 'b'
editor: visual
geometry:
      - inner=1cm
      - outer=1cm
      - top=1cm
      - bottom=1cm
---

**Research question**: Is there a difference between the chicks' weights across the diet groups?

# Question 1

## Formulate a one-way ANOVA model for the problem

The one-way ANOVA model is:

$$
Y_{ij} = \mu + \alpha_j + \epsilon_{ij} \quad \text{for} \quad i = 1, \ldots, 71; \quad j = 1, \ldots, 6; \quad \epsilon_{ij} \sim \text{iid} \, N(0, \sigma^2)
$$

where $Y_{ij}$ is the $i$-th weight from the $j$-th feed, and $\alpha_j$ is the effect for the $j$-th feed group.

## Formulate the null hypothesis and the alternative

The hypotheses associated with the model are:

$$
H_0 : \alpha_1 = \alpha_2 = \cdots = \alpha_6 = 0
$$

$$
H_1 : \text{at least one } \alpha_j \text{ is different from } 0
$$

## Formulate the test statistic

The test statistic is given as:

$$
F = \frac{\sum_{j=1}^6 n_j (\bar{x}_j - \bar{x})^2 / 5}{\sum_{j=1}^6 \sum_{i=1}^{n_j} (x_{ij} - \bar{x}_j)^2 / 65}
$$

and the critical value is found in a table of probability values for the F distribution with degrees of freedom $\text{df}_1 = 5$ and $\text{df}_2 = 65$. Also, $n_j$ is the sample size in the $j$-th group, $\bar{x}_j$ is the sample mean of the $j$-th group, and $\bar{x}$ is the overall mean.

## Test the null hypothesis using the classical $F$-test and test the null hypothesis using a significance level of 5%.